### PR TITLE
Release: 2021/05/12

### PR DESCRIPTION
**Pull request by cafca**

### CODE REVIEW

**Review by cafca — COMMENTED** [review]
looks good

**Comment by okdistribute** [comment]
@cafca is this ready to go? do you want us to merge it when we're ready?

**Comment by cafca** [comment]
Will do

**Comment by cafca** [comment]
The "see pattern library" vertical button placement on the landing page seems off to me. I will publish regardless, I hope that's okay. I am sick and don't really want to be on the computer much right now ;)

**Pull request merged**
